# Generated by Django 2.1.7 on 2019-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makenotes',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
