# Generated by Django 2.1.7 on 2019-06-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190613_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makenotes',
            name='text',
            field=models.TextField(),
        ),
    ]
