# Generated by Django 2.1.7 on 2019-06-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190613_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makenotes',
            old_name='text',
            new_name='Enter',
        ),
    ]
