# Generated by Django 2.1.7 on 2019-06-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190614_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makenotes',
            old_name='Enter',
            new_name='Text',
        ),
    ]
