# Generated by Django 2.2.1 on 2019-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylog_app', '0002_auto_20190604_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
