# Generated by Django 2.1.7 on 2019-06-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paylog_app', '0004_post_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_details',
        ),
    ]
