# Generated by Django 2.1.7 on 2019-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylog_app', '0005_delete_post_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
