# Generated by Django 2.1.7 on 2019-06-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylog_app', '0007_auto_20190616_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
